[package]
name = "mpd_rs_interface"
version = "0.3.0"
authors = ["r3b311i0n <nasashinega@gmail.com>"]

[dependencies]
mpd = "*"
serde = "1.*.*"
serde_json = "1.*.*"
serde_derive = "1.*.*"
colored = "1.6"
xdg = "^2.1"